name: Test and Reports

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Grant permissions for user space Icmp
        run: sudo sysctl -w net.ipv4.ping_group_range="0   2147483647"
      - name: Build with Gradle
        run: ./gradlew clean assemble --no-build-cache
      - name: JVM unit Tests with Coverage Report
        run: ./gradlew check
      # tar the reports since its much faster uploading multiple files
      - name: Tar Reports
        if: always()
        run: |
          pwd
          ls -la
          mkdir -p ./core/build/reports/ &&
          tar -czvf kanonproxy-reports.tar.gz -C core/build reports
      - name: Upload Reports
        uses: actions/upload-artifact@v4.4.3
        if: always()
        with:
          name: kanonproxy-reports
          path: kanonproxy-reports.tar.gz
      - name: Upload Lib Unit Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: libunittests
          files: ./core/build/reports/jacoco/test/jacocoTestReport.xml
# TODO: need to debug why creating the tun/tap is failing - perhaps not possible on GH runners
#      - name: End to End Tests
#        run: |
#          bash client/scripts/tuntap.sh $USER
#          ./gradlew :client:run &
#          ./gradlew :server:run &
#          sleep 5
#          ping -I kanon -c 5 8.8.8.8
#          curl --interface kanon https://www.google.com
#          bash client/scripts/cleanup.sh
